name: Release
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup LLVM / Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Compile Native headsetcontrol.dll
        shell: cmd
        run: |
          call build_native.bat

      - name: Build Applications
        shell: cmd
        run: |
          call build.bat

      - name: Compile Inno Setup Installer
        run: ISCC.exe installer.iss

      - name: Create Portable Zip
        shell: pwsh
        run: |
          Compress-Archive -Path HeadsetControlTaskbarBatteryIndicator.exe, HeadsetControlTaskbarBatteryIndicatorConsole.exe, headsetcontrol.dll -DestinationPath Output\HeadsetControlBatteryIndicator-Portable.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Output/HeadsetBatteryIndicatorSetup.exe
            Output/HeadsetControlBatteryIndicator-Portable.zip
          draft: false
          generate_release_notes: true
